definitions:
  router.HelloResponse:
    properties:
      mess:
        type: string
    type: object
  router.Length:
    properties:
      length:
        type: integer
    type: object
  router.Print:
    properties:
      print:
        type: string
    type: object
info:
  contact: {}
paths:
  /end:
    delete:
      description: Delete the last element in the linked list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.HelloResponse'
      summary: Delete the last element
  /end/{key}:
    post:
      description: Insert a new element at the end of the linked list
      parameters:
      - description: Key parameter
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.HelloResponse'
      summary: Insert data at the end
  /front:
    delete:
      description: Delete the first element in the linked list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.HelloResponse'
      summary: Delete the first element
  /length:
    get:
      description: Retrieve and return the number of elements in the linked list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.Length'
      summary: Retrieve the length of the linked list
  /print:
    get:
      description: Retrieve all elements in the linked list and return them as a concatenated
        string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.Print'
      summary: Retrieve all elements
  /start/{key}:
    post:
      description: Insert a new element at the beginning of the linked list
      parameters:
      - description: Key parameter
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.HelloResponse'
      summary: Insert data at the start
swagger: "2.0"
